### ISSUE TITLE
Question: What is the difference here with your m4q?

### ISSUE THREAD

**Issue by Mashiane** [olton/query#1]
Hi, Im just going through your stuff. lovely?

What is the difference here between this lib and the m4q lib?

**Comment by olton** [comment]
Hi! This is the next version of M4Q for Metro 5 (such as Datetime, String, Animation, Color, and others). Soon the development of Metro 4 will stop completely and I will concentrate on maintaining the existing code on a paid subscription and the development of Metro 5. Unlike Metro 4, which is monolithic, Metro 5 will be modular, and this is a part of it.
